### ISSUE TITLE
How to add global headers with `onRequest` when using $fetch.create

### ISSUE THREAD

**Issue by nanaaikinson** [unjs/ofetch#102]
With axios, one can add global headers to config just like below

```js
const instance: AxiosInstance = axios.create({
  baseURL: baseUrl,
  withCredentials: true,
});

// Add a request interceptor
instance.interceptors.request.use(
  function (config) {
    const token = ls.getItem("alva.accessToken");
    config.headers = {
      Authorization: `Bearer ${token}`,
    };

    return config;
  },
  function (error) {
    return Promise.reject(error);
  }
);
```

**Comment by ikexing-cn** [comment]
```ts
export const useCustomFetch = $fetch.create({
  baseURL: 'http://localhost:4000/',
  async onRequest({ options }) {
    const count = 0;
    options.headers = {
      customs: `count: ${count}`,
    }
  },
})
```

it's works fine and does not replace the individually requested headers.

**Comment by alzaabi98** [comment]
> ```ts
> export const useCustomFetch = $fetch.create({
>   baseURL: 'http://localhost:4000/',
>   async onRequest({ options }) {
>     const count = 0;
>     options.headers = {
>       customs: `count: ${count}`,
>     }
>   },
> })
> ```
Thanks @johannschopplich 
How  to use this one ? is it composable file  ? or just simple js file ?

**Comment by johannschopplich** [comment]
Use it wherever you want – in a JS file (make sure to add the `$fetch` import) or as a composable.

**Comment by Matman94** [comment]
> Another example to re-use other headers:
> 
> ```ts
> export const useApi = $fetch.create({
>   async onRequest({ options }) {
>     const authStore = useAuthStore();
>     if (!authStore.isLoggedIn) return;
>     await authStore.refresh();
>     options.headers = new Headers(options.headers);
>     options.headers.set("Authorization", `Bearer ${authStore.idToken}`);
>   },
> });
> ```

Hi,
Where should I place above code? In Quasar is simply, just place in boot directory and register in config. But in nuxt?

**Comment by Valar103769** [comment]
> ```ts
> export const useCustomFetch = $fetch.create({
>   baseURL: 'http://localhost:4000/',
>   async onRequest({ options }) {
>     const count = 0;
>     options.headers = {
>       customs: `count: ${count}`,
>     }
>   },
> })
> ```

i think this can overwrite else headers
