### ISSUE TITLE
$fetch() doesn't work with golang server in nuxt3?

### ISSUE THREAD

**Issue by Rusinas** [unjs/ofetch#110]
$fetch() in nuxt 3 gives me weird error `fetch failed ()` when calling endpoint in golang server.

I described the problem in details here: https://stackoverflow.com/questions/73098374/nuxt-3-fetch-method-doesnt-work-with-golang-servers

You can just check my reproduction: https://github.com/Rusinas/nuxt-fetch-bug

**Comment by kissu** [comment]
Maybe related to this one: https://github.com/unjs/ohmyfetch/issues/90

Not sure if this one may help or not: https://github.com/unjs/ohmyfetch/issues/52
