### ISSUE TITLE
Bypass Error in Nuxt 3

### ISSUE THREAD

**Issue by YuLogun** [unjs/ofetch#114]
Hi!
I cannot understand the example in docs regarding bypassing errors https://github.com/unjs/ohmyfetch#%EF%B8%8F-handling-errors

My use case is the following:
In my Nuxt 3 app I have a filter on the page (it consists of several selects). Whenever the filter changes, I use its values (`debouncedFetchQuery.value`) to fetch data (with Nuxt 3 `useAsyncData` composable):

```typescript
let controller = new AbortController();
const authToken = computed(() => authStore.authToken);
const {
    data: categories,
    pending: isCategoriesPending,
    refresh,
    error: categoriesError
} = await useAsyncData('fetch-categories-key', () => $fetch('/api/transactions', {
    baseURL,
    params: debouncedFetchQuery.value,
    signal: controller.signal,
    headers: { Token: authToken.value || '' }
}), {
    initialCache: false
});

let pendingRefresh = null;
watch(debouncedFetchQuery, async () => {
    if (isCategoriesPending.value) {
        controller.abort();
        controller = new AbortController();
    }

    if (pendingRefresh) {
        await pendingRefresh;
    }
    pendingRefresh = refresh();
});
```

The problem I have is that whenever request aborts, `useAsyncData` returns `null` for data and its subsequent component disappears from the page until the next successful request.

I wonder if it's possible to bypass Abort errors so as Nuxt composable would ignore them?

**Comment by YuLogun** [comment]
My solution for now is the following:

```
const categoriesOptions = ref();
watch(() => categories.value, () => {
    if (categories.value) {
        // update categoriesOptions here for page render
    }
});
```

**Comment by NozomuIkuta** [comment]
I feel this issue is potentially related to and/or duplicated of #160.
But, we appreciate if you provide a minimal reproduction by which everyone can see what you see.

**Comment by pi0** [comment]
Let's track via https://github.com/unjs/ofetch/issues/160 (or feel free to open an issue/question in nuxt/nuxt and ping me 👍🏼 )
