### ISSUE TITLE
HTTPS agent for CA CERT validation?

### ISSUE THREAD

**Issue by gjovanov** [unjs/ofetch#116]
Hi there,
I wasn't able to find any option to provide a CA CERT file for HTTPS cert validation.
E.g. something like this:

`const httpsAgent = new https.Agent({ ca: MY_CA_BUNDLE });`

Is this possible to do this with ohmyfetch and if so, how?
(Already asked the same question in [here](https://github.com/unjs/ohmyfetch/issues/34), but since it's already a closed issue, I'm opening a new one).
Thanks.

**Comment by macdows** [comment]
Any updates on this?

I really don't see `NODE_TLS_REJECT_UNAUTHORIZED=0` as a safe alternative...

**Comment by danwritecode** [comment]
Also looking for a solution on this.

**Comment by NozomuIkuta** [comment]
ohfetch utilizes global `fetch` if available (Node.js v16.15.0+), whose API is compatible with browser's `fetch` and has no option for HTTP(S) agent.

Currently, No such API as `ofetch.nodeFetch` is provided like `ofetch.raw` and `ofetch.native`.

So, if I'm correct, there is no way to achieve your goal at the moment.

---

@pi0 

If I'm not correct, please correct me and the issue label. But if I'm correct, taking Node.js LTS version into consideration, there would be less and less chance where `node-fetch` is picked up as ohfetch internal. So, it would be beneficial to provide a way developers can arbitrarily choice `node-fetch`.

**Comment by pi0** [comment]
Types don't allow it but actually you can pass an agent via `agent` config. 

Example: https://github.com/nuxt/nuxt/blob/7b35a1fe4faed49fffe3427a0db4aabae138f4ae/packages/vite/src/runtime/vite-node-shared.mjs#L11

Related: https://github.com/unjs/node-fetch-native/issues/87

I think we might introduce docs. PR welcome for that!
