### ISSUE TITLE
QA: Response Snake -> Camel; Request (body, query) Camel -> Snake

### ISSUE THREAD

**Issue by san4io** [unjs/ofetch#118]
Hello.

Maybe someone can give me an idea where should I put the logic of converting properties?

Interceptor? Or just wrap fetch with some function that converts, and calls "wrapper".

**Comment by huynl-96** [comment]
@san4io 
You can try 
- Using `decamelizeKeys`  on `query`/`body` inside [`onRequest`](https://github.com/unjs/ohmyfetch#onrequest-request-options-) interceptor 
- Using `camelizeKeys` on `response._data` when `responseType` is `json`  inside [`onResponse`](https://github.com/unjs/ohmyfetch#onresponse-request-options-response-) interceptor

Checkout [humps](https://github.com/domchristie/humps) for utilities related to `(de)camelization` 

```ts
async onRequest({ options }) {
  if (options.params) {
    options.params = decamelizeKeys(options.params)
  }
}
```

**Comment by pi0** [comment]
Nice solution @huynl-96. I would suggest using [unjs/scule](https://github.com/unjs/scule) which is a better alternative to humps.

**Comment by huynl-96** [comment]
Nice, I've just had a quick look at `scule`, definitely gonna give it a try. 
Thank @pi0 for the suggestion

**Comment by command-tab** [comment]
I'm interested in doing this, as well. In `onResponse`, should I just _replace_ `response._data` with the case-modified version like this?

```ts
onResponse({ request, response, options }) {
   response._data = camelCaseKeys(response._data, { deep: true })
}
```

Returning a case-modified object doesn't seem to affect the result downstream:

```ts
onResponse({ request, response, options }) {
   return camelCaseKeys(response._data, { deep: true })  // Data in my Nuxt app is still snake_case
}
```

The [documentation](https://github.com/unjs/ofetch#onresponse-request-options-response-) for the `onResponse` interceptor shows how to read the response data, but isn't clear on how to modify it before it goes on its way.
