### ISSUE TITLE
$fetch not catching error

### ISSUE THREAD

**Issue by david4bou** [unjs/ofetch#131]
Hello everyone ! I'm on nuxt^3.0.0.rc-11 and I want to make a function that check if a file exist.
For now my function looks like this:
```
const isFileExist = async (path: string) => {
    try {
        await $fetch(path)
        return true
    } catch (e) {
        return false
    }
}
```
but in my console I have this error displayed instead of catched
```
GET http://localhost:3000/path.jpg
[HTTP/1.1 404 Page not found: path.jpg 25ms]
```

**Comment by manniL** [comment]
Resolved in https://github.com/nuxt/framework/issues/7941
