### ISSUE TITLE
Merge default options with call options

### ISSUE THREAD

**Issue by localusercamp** [unjs/ofetch#133]
Hello there!

Using the library in `nuxt 3` i found the following problem:
```javascript
const myfetch = $fetch.create({
  baseURL: 'base',
  headers: {
    'Header1': 'value',
  },
});

myfetch('route', { headers: { 'Header2': 'value' } });
```
In this example i expect that `myfetch` call will contain 2 headers: `'Header1'` and `'Header2'`, but insted `myfetch` call overrides default options completely. Can it be solwed?

I think there can be two approaches: 

1. Rework options merge mechanisms.
2. Add some kind of persisted options as second argument of `$fetch.create()` that will be merged, not replaced by `myfetch` call.

**Comment by NozomuIkuta** [comment]
I believe your question will be resolved by https://github.com/unjs/ofetch/issues/102#issuecomment-1187698125.
Please reopen if you find it doesn't work in your case.
