### ISSUE TITLE
how can i modify url in request interceptor

### ISSUE THREAD

**Issue by jianxing-xu** [unjs/ofetch#146]
I need to uniformly modify the url in request interception, how can I do it， Thanks

**Comment by Tragio** [comment]
I have the same question. I'm migrating a web app to Nuxt 3. I thought manipulating the request parameter would change the outgoing request. In my use case, I need to append a cookie number to the URL. 

```js
const apiFetch = $fetch.create({
    credentials: 'include',
    baseURL: 'https://api.domain.com',
    onRequest: ({ request }) => {
      // get cookie and append to request
      request = "/test/"
      }
    },
})
```

@pi0 @danielroe is this a supported behavior?

**Comment by shba007** [comment]
I Created a Composable like this

    import { FetchOptions } from "ofetch";
    
    export const useAPI = (url: string, options: FetchOptions) => {
      const config = useRuntimeConfig()
    
      const customFetch = $fetch.create({
        baseURL: config.public.apiURL,
        headers: { 'Authorization': `Bearer ${"Test"}` },
        onRequest({ request, options }) {
          console.log("Intercepted API", request);
        }
      })
    
      return customFetch(url, options)
    }

**Comment by NozomuIkuta** [comment]
@jianxing-xu

`onRequest` hook receives `context` whose `request` is the first argument that you passed to `ofetch` function.
You can modify it as a string or a kind of object (e.g. [browser-compatible fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters), or [node-fetch](https://www.npmjs.com/package/node-fetch#fetchurl-options)), based on how you passed it.

https://github.com/unjs/ofetch/blob/ff697d7b4a43c4399897b69097485b3785dfd661/src/fetch.ts#L94-L104

**Comment by geminigeek** [comment]
> @jianxing-xu
> 
> `onRequest` hook receives `context` whose `request` is the first argument that you passed to `ofetch` function. You can modify it as a string or a kind of object (e.g. [browser-compatible fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters), or [node-fetch](https://www.npmjs.com/package/node-fetch#fetchurl-options)), based on how you passed it.
> 
> https://github.com/unjs/ofetch/blob/ff697d7b4a43c4399897b69097485b3785dfd661/src/fetch.ts#L94-L104

hi,

i am doing like this in onRequest but its not working ? can you give an example how to change url , i want to change url based on retry number 

```
if (options?.retry == 1) {
     request = "http://192.168.1.8:3010/status/200" // new url
      
  }
```

**Comment by gokhantaskan** [comment]
```ts
const $api = $fetch.create({
      baseURL: config.public.apiPath,
      credentials: "include",
      // Convert request body to snake_case
      onRequest({ request, options }) {
        const method = options.method || "GET";
        const noSlashMethods: string[] = ["get", "GET"];

        // If the method is not GET, add a trailing slash to the url
        if (
          typeof request === "string" &&
          !noSlashMethods.includes(method) &&
          !request.endsWith("/")
        ) {
          **request += "/";** // DOES NOT WORK
        }

        if (options.body) {
          options.body = JSON.stringify(changeObjectKeysCase(options.body, "snake"));
        }

       // @ts-expect-error
        **return $fetch(request, options);** // DOES NOT WORK EITHER ➔INFINITE QUERY DUE TO TRAILING SLASH ERROR
      },
      // Convert response data to camelCase
      onResponse({ response }) {
        if (typeof response._data === "object") {
          response._data = changeObjectKeysCase(response._data, "camel");
        }
      },
...
```

Is there a solution to this problem?

**Comment by gregpalaci** [comment]
Yeah this is an issue
```
export const fetchWithProxy = ofetch.create({
  onRequest: ({ request }) => {
    // get cookie and append to request
    let newReq = newFetch(request);
    console.log("Intercepted API", request);
    request = newReq;
    console.log("Intercepted API 2", request);
  },
});
```
string change no work

**Comment by oopatechinc** [comment]
I had a similar problem. In my case, I had to add xdebug string so my php backend can debug if required. Updating the options.query resolved the issue for me. Here is a code snippet. I am using nuxt4 plugin syntax but it's essentially the same.

Let's assume the request url before the interceptor is : `https://localhost/api/login`

```
export default defineNuxtPlugin((nuxtApp) => {
  const api = $fetch.create({
          baseURL:<BASEURL>,
  
          // Request Interceptor: runs before every fetch
          onRequest({options }) {
              options.query = options.query || {}; 
              options.query.XDEBUG_SESSION_START = 1;  
          }
      });
});
```

The request url will be updated with the new query so it becomes  https://localhost/api/login?XDEBUG_SESSION_START=1
