### ISSUE TITLE
Errors not forwarded in hooks

### ISSUE THREAD

**Issue by wagpa** [unjs/ofetch#148]
When an error occurs in the `onRequest` hook, the error is not shown in the console and no request is send.
I would expect an error that occurs in the hook to still be shown in the console.

The following will create a fetch object that makes no requests, but prints no error.
```js
$fetch.create({
  async onRequest(ctx): Promise<void> {
    throw "debug error"
  }
})

**Comment by pi0** [comment]
Let's track via https://github.com/unjs/ofetch/issues/396
