### ISSUE TITLE
Error 500 "fetch failed ()" at `$fetchRaw2`

### ISSUE THREAD

**Issue by prescience-data** [unjs/ofetch#156]
On a new Nuxt 3 installation, the demo page that should load when loading `pnpm run dev` crashes with

```
[nuxt] [request error] [unhandled] [500] fetch failed ()
  at async $fetchRaw2 (./node_modules/.pnpm/ohmyfetch@0.4.20/node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)  
  at async ./.nuxt/dev/index.mjs:537:20  
  at async ./.nuxt/dev/index.mjs:608:64  
  at async ./.nuxt/dev/index.mjs:107:22  
  at async Object.handler (./node_modules/.pnpm/h3@0.8.6/node_modules/h3/dist/index.mjs:634:19)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@0.8.6/node_modules/h3/dist/index.mjs:698:7)
```

Attempting to isolate, I have tried with the following variations: `node@18`, `node@19`, `pnpm`, `npm`, `yarn` - deleting the project and starting fresh each time, all with the same results.

Environment specifics that may be relevant:
- Ubuntu 22.04 _(popOS!)_
- [volta](https://volta.sh/) node version manager
- Nuxt 3.0.0-rc.12 with Nitro 0.6.0

I can't find any references to this issue on either the `nuxt` package or the intermediate `h3` page which indirectly calls `ohmyfetch`, so given the error seems to emerge from `$fetchRaw2` within the `ohmyfetch` package, thought it best to post here.

**Comment by tao** [comment]
I ran into this same problem on a brand new Nuxt `3.0.0-rc.12` install too. I tried Node v18 and v19 as I thought it was related to the fetch API warning that the CLI prints when you run the code.

```
ExperimentalWarning: The Fetch API is an experimental feature.
```

It's the same error line I'm getting.

```
FetchError: fetch failed ()
    at async $fetchRaw2 (file:///Users/tao/nuxt-frontend/node_modules/ohmyfetch/dist/shared/ohmyfetch.fb8dc89e.mjs:132:20)
```

**Comment by prescience-data** [comment]
I worked out from the Node 16 error message that it's due to an ipv6 issue (possibly downstream in Nuxt).

When you set `scripts` to run `nuxt dev --host 127.0.0.1` it works, but that was super-non-obvious lol.

**Comment by chrisnaadhi** [comment]
got same problem when using node v18
it's all gone when using node v16, better stick with v16 for a while

**Comment by Maximus1000** [comment]
Same 500 fetch error. Fresh nuxt-rc13. Nothing else in it.  
I'm wondering if anyone knows if I'm making a mistake on SSL / Certificate syntax in either config or package.json?
The error for me could be related to Node v18 (haven't downgraded yet) or due to something else related to SSL cert.

I tried with variations on the dev script, e.g. --host 127.0.0.1 or localhost or blank, same error. When I remove the cert and cert-keys in dev script, no 500 error (Nuxt splash loads correctly) but now HTTP not HTTPS (SSL not accepted).

The config below is being accepted by Chrome for HTTPS.  

Node: 18.7.0

```
500
fetch failed ()
at async $fetchRaw2 (/C:/code/nuxt3-b/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
at async /C:/code/nuxt3-b/.nuxt/dev/index.mjs:550:20
at async /C:/code/nuxt3-b/.nuxt/dev/index.mjs:624:64
at async /C:/code/nuxt3-b/.nuxt/dev/index.mjs:107:22
at async Object.handler (/C:/code/nuxt3-b/node_modules/h3/dist/index.mjs:634:19)
at async toNodeHandle (/C:/code/nuxt3-b/node_modules/h3/dist/index.mjs:698:7)
at async Object.ufetch [as localFetch] (/C:/code/nuxt3-b/node_modules/unenv/runtime/fetch/index.mjs:9:17)
at async Object.errorhandler [as onError] (/C:/code/nuxt3-b/.nuxt/dev/index.mjs:432:30)
at async Server.toNodeHandle (/C:/code/nuxt3-b/node_modules/h3/dist/index.mjs:705:9)
```

nuxt.config.ts
```
const fs = require('fs');
import {fileURLToPath} from "node:url";

export default defineNuxtConfig({
  devServer: {
    host: 'banana.test',
    https: {
      key: fs.readFileSync(fileURLToPath(new URL('./banana.test+4-key.pem', import.meta.url))),
      cert: fs.readFileSync(fileURLToPath(new URL('./banana.test+4.pem', import.meta.url))),
    }
  },
})
```

package.json
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --https --host banana.test --ssl-cert banana.test+4.pem --ssl-key banana.test+4-key.pem",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.13"
  }
}
```

SSL works in the above config (HTTPS accepted) and I get the 500 error.
With just ``dev: nuxt dev --https --host banana.test    `` or any other params (excluding cert and cert-key), no 500, no HTTPS, and Nuxt splash loads correctly.

If anyone has any suggestions, much appreciated.

**Comment by renanvnunes** [comment]
This may be happening because Nuxt is trying to run $fetch on the server side, while it should be done on the client side. Try this:

`if(process.client){
      await $fetch()
      // code...
}`

**Comment by pi0** [comment]
Hi. This seems an old issue with upstream ones closed. If still having issues, please consider opening a new issue in nuxt/nuxt with minimal reproduction and ping me 👍🏼

**Comment by TeodorDre** [comment]
Updating Node to 20.5 solved this problem. Not it works fine.

**Comment by alih70442** [comment]
just use node 16
