### ISSUE TITLE
POST JSON - Wrong content type

### ISSUE THREAD

**Issue by janschiefer** [unjs/ofetch#164]
If I try to post JSON-Data with node-fetch-native, the "Content-Type" header is always set to

text/plain;charset=UTF-8

by "const extractContentType = (body, request)".

This can be a serious issue with some backend frameworks, that send "Bad Request" responses with missing or incorrect Content-Type ( "application/json" is needed here ).

This is also a serious issue with the useFetch(...)-Wrapper ( the new default for fetching data ) in the new Version 3 of the popular Nuxt framwork ( wich uses node-fetch-native).

**Comment by janschiefer** [comment]
Thank you!

**Comment by pi0** [comment]
Hi. I cannot reproduce this issue anymore:

<img width="376" alt="image" src="https://github.com/unjs/ofetch/assets/5158436/3d9ef59a-a14c-42bc-b4d5-2e229fd81635">

Also on server-side when testing https://github.com/unjs/ofetch/issues/88#issuecomment-1203578878 seems undici issue was the cause.

If you still got the issue, please ping me to reopen and investigate together.
