### ISSUE TITLE
Request headers

### ISSUE THREAD

**Issue by svaldivia12** [unjs/ofetch#187]
Hello,

How can I access the 'Content-Disposition' header on the request response?

I tried using the interceptor onResponse and fetch.raw(), but both have the same problem, they completely ignore Content-Disposition.

Both of them just retrieve cache-control, content-length, content-type and last-modified.

Any help will be appreciated

Thanks

**Comment by NozomuIkuta** [comment]
Would you provide a minimal reproduction that describes what happens when you try to get `Content-Disposition` header, so that everyone can see what you see?
