### ISSUE TITLE
Renaming of the lib, from `ohmyfetch` to `ofetch` : why ?

### ISSUE THREAD

**Issue by qnp** [unjs/ofetch#190]
### Describe the feature

Greetings,

I did not find a discussion tab on that lib so I ask my question here - why did you choose to rename `ohmyfetch` into `ofetch` and its exports `$fetch` to `ofetch` ?

I have not seen any resource on it nor read any discussion about it. What did motivate this choice ?

Best,

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi dear @qnp. Rename happened during updating the version to stable but indeed without notice. I had been waiting for a shorter `ofetch` package which was unavailable at the time and renamed before widely adopting the name for Nuxt 3 release.

There will be another release for ohmyfetch with instructions to upgrade and rename package also reexporting latest ofetch.

The new export alias `ofetch` (`$fetch` will be supported) helps to recognize the interface and relevant package as `$fetch` was more cryptic.  

Please let me know if you have any more questions :)
