### ISSUE TITLE
Detect network errors for Node.js environment

### ISSUE THREAD

**Issue by oleynikd** [unjs/ofetch#193]
### Describe the feature

If user is offline any https request will end up with `net::ERR_INTERNET_DISCONNECTED`, but ofetch throws `FetchError: Failed to fetch ()` without any way to find out that user is offline

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Since it is only possible for node.js entry, we might support an option to transform error message and pass it internally.

**Comment by oleynikd** [comment]
I'm talking about client side, not server side requests. Actually most browsers support this API: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine
Maybe use it for network status detection?
Now if you try to call `fetch()` while offline in Chrome you'll get:
<img width="558" alt="Screenshot 2022-12-23 at 18 00 55" src="https://user-images.githubusercontent.com/3976868/209364445-cd38ad06-fc6c-4690-ba36-fc75d43ed196.png">

**Comment by NozomuIkuta** [comment]
`fetch` that is internally used by ofetch differs from server side to client side. 

I think implementing a logic that depends on browser-only API (i.e. `navigator`) in `ofetch` brings complexity and make the package harder to maintain (additionally, although there also seems to be a way to check internet connectivity in Node.js, it's hacky and irresponsible).

IMHO, `ofetch` should be kept simple and aways try to send request whenever it's called, regardless of the network situation, and instead a wrapper logic should be implemented, which checks network situation and determines whether it should call ofetch.

In the context of Nuxt, composables could be such a wrapper.
