### ISSUE TITLE
ofetch.create is not a function

### ISSUE THREAD

**Issue by daguanren21** [unjs/ofetch#198]
### Environment

node version is 14.18.0,ofetch version is 1.0.0

### Reproduction

![image](https://user-images.githubusercontent.com/56297137/207486644-1049d62b-66fe-4b2c-9444-07269e4cadbf.png)

### Describe the bug

I want to use ofecth.create function to create baseUrl,but appear ofetch.create is not a function . plz

**Comment by Shyam-Chen** [comment]
Use `createFetch `

**Comment by Shyam-Chen** [comment]
```ts
import { ofetch } from 'ofetch';

const fetch = ofetch.create({ baseURL: '/api' });

console.log(fetch);
// [Function: $fetch2] {
//   raw: [AsyncFunction: $fetchRaw2],
//   native: [Function (anonymous)],
//   create: [Function (anonymous)]
// }
```

**Comment by NozomuIkuta** [comment]
@daguanren21 

Would you provide a minimal reproduction instead of a screenshot and reopen this issue later?

**Comment by markbrouch** [comment]
This seems to be an issue with cjs exports.

cjs (create is not a function): https://stackblitz.com/edit/node-9rgwsr?file=index.js

module (create runs correctly): https://stackblitz.com/edit/node-wqz68m?file=index.js
