### ISSUE TITLE
Access Request info in interceptors hooks

### ISSUE THREAD

**Issue by aliyr** [unjs/ofetch#204]
### Environment

Nuxt 3 using $fetch

### Reproduction

https://gist.github.com/aliyr/630622e6d9b6991e0f708dabc1e4a86d

### Describe the bug

I need to get request default data like default headers, but "request" is not an object but it's a string representing the requested route.

**Comment by julien-terral** [comment]
Hi aliyr, you need to use:
`request.headers.get('User-Agent')` instead of `request.headers['User-Agent']`

**Comment by aliyr** [comment]
> Hi aliyr, you need to use: `request.headers.get('User-Agent')` instead of `request.headers['User-Agent']`

Thank you @julien-terral, It will do

**Comment by aliyr** [comment]
@julien-terral I added this in my code and this error happened:

Error: Cannot read properties of undefined (reading 'get')

Also my Editor throws me this error:

TS2339: Property 'headers' does not exist on type 'RequestInfo'.   Property 'headers' does not exist on type 'string'.

Any ideas?

**Comment by julien-terral** [comment]
I reproduce the exact same issue by my end :/
I have this error `TypeError: Cannot read properties of undefined (reading 'get')` when I'm trying to get headers.

**Comment by aliyr** [comment]
I found the solution, 
You shouldn't destruct the arguments of the function nor use `.get` method.
 
This is the code that works for me by setting header on data

```
onRequest(req) {
      req.options.headers = {
        ...(req.options.headers || {}),
        'some-header': 'some data'      
      }
}
```
