### ISSUE TITLE
Fix package.json for react-native

### ISSUE THREAD

**Issue by qnp** [unjs/ofetch#206]
### Environment

React Native / Metro

### Reproduction

The lib is not usable in React Native context. 
Metro won't resolve properly the correct build in package.json: 
- He, by default, will look at `"main"` entry which is the node one.
- He also fails because he expects the entry `package.json` in `"exports"` (don't ask me why).
(one could be inspired by [axios package.json](https://github.com/axios/axios/blob/v1.x/package.json) which is well tested for node, browser and react-native)

### Describe the bug

1) React Native app will fail on `import http from 'node:http'` because it uses the node build.
2) Then, if corrected, it will ignore the package because `package.json` is not found in package.json 🙈 

### Additional context

In package.json, do these updates:
```diff
-    "main": "./cjs/node.cjs",
+    "main": "./cjs/index.cjs",
```
and
```diff
  "exports": {
+    "./package.json": "./package.json"
```

Beware that this should also be done in all `unjs` (awesomes) packages so that they can be used standalone in React Native.

**Comment by pi0** [comment]
Hi @qnp. I think would be nice addition for `node-fetch-native`/`ofetch` and direct dependencies of them to expose `package.json` subpath making it work with react-native 👍🏼 

BTW did you find any upstream reference in RN community about this issue? (they should normally handle it better)
