### ISSUE TITLE
Any way to support `onUploadProgress` like axios does?

### ISSUE THREAD

**Issue by vedmant** [unjs/ofetch#216]
### Describe the feature

I'm migrating my project from Nuxt 2 to Nuxt 3, I was using axios and `onUploadProgress` method on some requests. How I can do the same with `ofetch`?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by cedric-legallo** [comment]
if it may help it is somewhat possible using content-length and ReadableStream with the native fetch which is wrapped.

**Comment by pi0** [comment]
Let's track via https://github.com/unjs/ofetch/issues/45 👍🏼
