### ISSUE TITLE
关于请求的时候，get请求不能添加body ,所以请内部解决调一下

### ISSUE THREAD

**Issue by ReginYuan** [unjs/ofetch#226]
### Describe the feature

如图显示报错信息为：TypeError: Failed to execute ‘fetch’ on ‘Window’: Request with GET/HEAD method cannot have body.
大意是：未能在"窗口"上执行"fetch"：使用 GET/HEAD 方法请求不能具有主体。
原因是因为接口是get，但是又标注以requestbody（请求体）来接收参数。
说明：在get请求体中不能使用@requestBody来做请求的。

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by so1ve** [comment]
Please provide a minimal reproduction.

And as the error message says, you cannot use `body` in `GET` requests .
