### ISSUE TITLE
Feature Request: AbortController shortcut syntax

### ISSUE THREAD

**Issue by willin** [unjs/ofetch#23]
ref: https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by MichaelGitArt** [comment]
😶

**Comment by bloor** [comment]
A request-abort is much needed, especially for React/Vue projects.
Please provide a solution.

**Comment by xuxucode** [comment]
It does support `AbortController`. `$fetch` accepts options whatever  you passed in: https://github.com/unjs/ohmyfetch/blob/main/src/fetch.ts#L127.

For example:
```js
  const controller = new AbortController();
  const signal = controller.signal;
  $fetch(url, { signal });

  controller.abort();
```

**Comment by Valar103769** [comment]
It's not very good, but there's no problem with the wo

usage

```js
const request = useRequest()
const getList = async () => request('../',{method:'POST'})
```

useRequest
```js
export const  useRequest = () => {
  const controller = new AbortController()
  const signal = controller.signal

  const run = async (url: string, config: FetchOptions) =>
   $fetch(url, {
      ...config,
      signal,
    }).catch((e) => {
      if (e.message !== "Failed to execute 'fetch' on 'Window': The user aborted a request. ()") {
        throw e
      }
      return new Promise(() => {})
    })

  onUnmounted(() => {
    console.log('onUnmounted:request')

    controller.abort()
  })
  return run
}
```

**Comment by bf** [comment]
AbortController already works like @xuxucode has posted. I tried it. I think we can close this!

**Comment by pi0** [comment]
Indeed. AbortController is supported univerally. I was keeping issue open if we can make a better shortcut syntax for ofetch for canceling requests..

**Comment by CaptainFalcon92** [comment]
In case it could help as inspiration, vueuse provides an abort() function from its version of useFetch()
https://github.com/vueuse/vueuse/blob/main/packages/core/useFetch/index.ts#L359
https://vueuse.org/core/useFetch/#aborting-a-request

The AbortController instance is created internally.

**Comment by pi0** [comment]
We expose an auto polyfilled version of `AbortController` with https://github.com/unjs/ofetch/pull/268

**Comment by MickL** [comment]
> In case it could help as inspiration, vueuse provides an abort() function from its version of useFetch() https://github.com/vueuse/vueuse/blob/main/packages/core/useFetch/index.ts#L359 https://vueuse.org/core/useFetch/#aborting-a-request

I would also prefer to have a simple `abort()` function
