### ISSUE TITLE
Infinity loading in Stackblitz

### ISSUE THREAD

**Issue by SeryiBaran** [unjs/ofetch#233]
Hello!

When I try to import `ofetch` in default Stackblitz typescript template, I get errors like this and the sandbox won't load:
![image](https://user-images.githubusercontent.com/82605415/233782295-80cf9be9-3965-41cc-875c-aa370e3bfa27.png)

Demo [here](https://stackblitz.com/edit/typescript-szkx3p?file=index.ts).

**Comment by peterroe** [comment]
You should choose container with `Nodejs` like: https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-nmp34c?file=README.md

**Comment by SeryiBaran** [comment]
> You should choose container with `Nodejs` like: [stackblitz.com/edit/stackblitz-webcontainer-api-starter-nmp34c?file=README.md](https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-nmp34c?file=README.md)

Thanks, this works, but why...

**Comment by peterroe** [comment]
If you decide to use npm packages on stackblitz, you will most likely need a `nodejs` environment to help it run perfectly.
URL schema node just support above `node@16`
