### ISSUE TITLE
Error type is different if `responseType: "blob"` is specified

### ISSUE THREAD

**Issue by MAXOUXAX** [unjs/ofetch#234]
### Environment

Using the useFetch() composable from Nuxt 3.4.2

### Reproduction

```ts
const { error } = useFetch("/api/xyz", {
  responseType: "blob"
})

// if an error is returned, the `data` field won't be properly filled (it's an empty JSON object)
```

```ts
const { error } = useFetch("/api/xyz")

// if an error is returned, the `data` field will be correct and contain all the fields (statusMessage, data, etc)
```

### Describe the bug

The error object returned by the `useFetch` composable from Nuxt 3.4.2 which uses ofetch under the hood won't be the correct type if the `responseType` is defined as `"blob"` (and maybe other types, didn't investigate).
The data field will be an empty JSON object and therefore the data field given in the `createError()` call won't be available, as well as other non-transformed fields such as `message`.

**Comment by Hebilicious** [comment]
@pi0 Can this be moved to nuxt ?

**Comment by pi0** [comment]
A reproduction from nuxt/nuxt repository would be appreciated 👍🏼 (if it is reproducable with ofetch only we can keep tracking here)
