### ISSUE TITLE
Incompatibility with Next.js Edge API runtime using `edge-light` condition

### ISSUE THREAD

**Issue by pajecawav** [unjs/ofetch#238]
### Environment

ofetch: v1.0.1
next: from v13.1.7-canary.17 to v13.4.1
node: v18.15.0

### Reproduction

https://github.com/pajecawav/next-ofetch-edge-api-route

To reproduce:
```sh
git clone https://github.com/pajecawav/next-ofetch-edge-api-route
cd next-ofetch-edge-api-route
pnpm install
pnpm build
```

### Describe the bug

Starting from [next@13.1.7-canary.17](https://github.com/vercel/next.js/releases/tag/v13.1.7-canary.17) I can't use `ofetch` inside an [Edge API route](https://nextjs.org/docs/pages/building-your-application/routing/api-routes#edge-api-routes) because build fails with an error `"Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme)."`.

After some digging I figured out that most likely changes in [this PR](https://github.com/vercel/next.js/pull/45188/files) caused the issue.

I managed to get it working by removing `"node"` section from `"exports"` field in the `package.json`  of `ofetch`:

```diff
diff --git a/package.json b/package.json
index f182539..a921c1b 100644
--- a/package.json
+++ b/package.json
@@ -8,11 +8,6 @@
   "type": "module",
   "exports": {
     ".": {
-      "node": {
-        "types": "./dist/node.d.ts",
-        "import": "./dist/node.mjs",
-        "require": "./dist/node.cjs"
-      },
       "default": {
         "types": "./dist/index.d.ts",
         "import": "./dist/index.mjs",
```

Adding `"edge-light"` also seems to fix the issue:

```diff
diff --git a/package.json b/package.json
index f182539..cbafb2c 100644
--- a/package.json
+++ b/package.json
@@ -8,6 +8,11 @@
   "type": "module",
   "exports": {
     ".": {
+      "edge-light": {
+        "types": "./dist/index.d.ts",
+        "import": "./dist/index.mjs",
+        "require": "./dist/index.cjs"
+      },
       "node": {
         "types": "./dist/node.d.ts",
         "import": "./dist/node.mjs",
```

**Comment by pi0** [comment]
Thanks for reporting this. Let me do some more research how reliable is this new condition. FYI we had been thinking to introduce similar condition for Nitro/Nuxt (https://github.com/unjs/nitro/issues/1123)
