### ISSUE TITLE
Pre-operate with response in the interceptor

### ISSUE THREAD

**Issue by MaxNvk** [unjs/ofetch#257]
### Describe the feature

I'm wondering have the ability to prepare a response in the onResponse interceptor to simplify working with responses in a more high level of code.
For example:

```
const fetchInstance = ofetch.create({
    baseURL: config.public.baseURL,
    headers: {
      Authorization: '',
    },
    onResponse({ response }) {
      return response._data.data;
    },
});

```

```
const { token } = $fetchInstance('/files/createMediaFileToken', {
  body: payload,
  method: 'POST',
})
```

Here I've received a response with a token field, and I wanna pick 'token' by object destructuring like `const { token }` but not like `const { data: { token } }`. So using an onResponse interceptor with the code described above helps me to simpler object destructuring.

**Comment by pi0** [comment]
Hi. I believe you can actually do it already; you only need to _modify_ the same `_data`:

```ts
const fetchInstance = ofetch.create({
    baseURL: config.public.baseURL,
    headers: {
      Authorization: '',
    },
    onResponse(ctx) {
      ctx.response._data = ctx.response._data.data;
    },
});
```

Please let me know if you have any questions (also PR welcome to improve docs!)
