### ISSUE TITLE
Pass custom `fetch` function

### ISSUE THREAD

**Issue by KaKi87** [unjs/ofetch#260]
### Describe the feature

Hello,

It would be nice to be able to pass a specific `fetch` function to wrap with `ofetch`, so that it could be used in peculiar environments such as [SvelteKit's SSR `load` function](https://kit.svelte.dev/docs/load#making-fetch-requests).

Thanks

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. It is possible with `createFetch`. This is how we pass Nitro Local Fetch as well: https://github.com/unjs/nitro/blob/ce5d22340c26ae428f062d43f54d1b8aa7344ecd/src/runtime/app.ts#L105

Let me know if you have any questions about doing this 👍🏼

**Comment by pi0** [comment]
PR welcome to improve docs!

Headers is to provide headers polyfill. Normally ofetch does this automatically

**Comment by KaKi87** [comment]
> PR welcome to improve docs!

Alright, I'll consider it once I'll have some experience using `ofetch` in production.

> Headers is to provide headers polyfill. Normally ofetch does this automatically

What does it do ?

**Comment by pi0** [comment]
It is a constructor for headers. Read more: https://developer.mozilla.org/en-US/docs/Web/API/Headers

**Comment by KaKi87** [comment]
So, if I don't import `Headers` from `ofetch` and pass it to `createFetch` then the lib won't support sending and/or receiving headers in requests ?

**Comment by pi0** [comment]
Latest versions of Node.js, already have global `Headers`. you should be fine! (the nitro code example is for legacy reasons that is explicitly passing it)

**Comment by KaKi87** [comment]
Alright. However, my IDE says the object is invalid when not passing it.

**Comment by pi0** [comment]
I see. Do you mind to open a new issue so i don't forget to put a fix? 🙏🏼

**Comment by pi0** [comment]
(in the meantime you can simply use `Headers: globalThis.Headers` or ignore type issue)

**Comment by KaKi87** [comment]
> Do you mind to open a new issue so i don't forget to put a fix? 🙏🏼

[Done](/unjs/ofetch/issues/266).

**Comment by picunada** [comment]
@KaKi87, @pi0 

Hello, I had no problem with SvelteKit SSR load function and using ofetch in it.

### `ofetch` usage in sveltekit SSR load function

Look at `lib/ofetch.ts` on how to create instance of ofetch with global `Headers` obj.

```ts
import {createFetch, Headers} from "ofetch";

export const $fetch = createFetch({
    fetch: fetch,
    Headers,
})
```

And use it as always in `src/routes/+page.ts`

```ts
import {$fetch} from "$lib/ofetch";

// since there's no dynamic data here, we can prerender
// it so that it gets served as a static asset in production
export const prerender = true;

/** @type {import('./$types').PageLoad} **/
export async function load() {

    const res = await $fetch("https://petstore.swagger.io/v2/store/inventory");
    const item = res;

    console.log(item)

    return { item };
}
```


here's example:
[codesanbox](https://codesandbox.io/p/sandbox/objective-colden-5gqvhc?file=%2Fsrc%2Froutes%2F+page.svelte%3A40%2C11)

**Comment by KaKi87** [comment]
I never said I had a problem, pi0's initial answer worked already, thanks anyway.
