### ISSUE TITLE
[Docs improvement] explanation of how retry is working

### ISSUE THREAD

**Issue by picunada** [unjs/ofetch#263]
### Describe the Improvement

Hello,

after reading the documentation, I wanted to use retry in my requests. I was confused as to why retries was not happening.

Digging around, I've found this issue [#109](https://github.com/unjs/ofetch/issues/109) which states that retries occurs if response code is included in list of retryStatusCodes. 

I suggest adding an explanation in which cases retries occurs to avoid confusion.

### Code block

```js
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
const retryStatusCodes = new Set([
  408, // Request Timeout
  409, // Conflict
  425, // Too Early
  429, // Too Many Requests
  500, // Internal Server Error
  502, // Bad Gateway
  503, // Service Unavailable
  504 //  Gateway Timeout
])

...

if (retries > 0 && retryStatusCodes.has(responseCode)) {
    return $fetchRaw(ctx.request, {
         ...ctx.options,
         retry: retries - 1
     })
}
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for PR!
