### ISSUE TITLE
Make it possible to get request method from error object

### ISSUE THREAD

**Issue by phorcys420** [unjs/ofetch#265]
### Describe the feature

```js
try {
  const res = await ofetch("https://url/that/returns/an/error");
} catch(e) {
  // typeof(e.request) === "string" -> true
  // I want to access request.method from the catch block
}
```

---

Is there a workaround ?
Am I doing this the wrong way around ?

---

The issue here is that ``FetchRequest``'s type boils down to ``string | Request``, and a ``string`` is being returned, which is rather unhelpful when you also need to access other properties from the request object.

```ts
declare class FetchError<T = any> extends Error {
    name: string;
    request?: FetchRequest;
    response?: FetchResponse<T>;
    data?: T;
    status?: number;
    statusText?: string;
    statusCode?: number;
    statusMessage?: string;
}
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by picunada** [comment]
Hello, as you use URL string to make request, context will contain request as string.
Workaround is to use Request object instead of URL string, I think this is how original fetch was envisioned to work.

```js
$fetch(new Request('http://api.com/post', {
    method: 'post',
    body: JSON.stringify({})
}), {
    // those will be overridden by Request object, even if not specified in Request object
    method: 'post',
    body: {
        
     }
})
```


example [codesandbox](https://codesandbox.io/p/sandbox/keen-montalcini-vp94nq?file=%2Fpages%2Findex.vue%3A39%2C27)

**Comment by picunada** [comment]
@KaKi87 
I don't understand why would you need to have `Request` and `FetchOptions` objects in `FetchError` object, if you control the request and options that you send to server.
Can you specify examples where this feature is needed?

**Comment by KaKi87** [comment]
Actually, I was only making this suggestion to solve OP's request.

Personally, I don't have such a use case.

But, since Axios provides this as well, I suppose it can be useful.

Thanks

**Comment by phorcys420** [comment]
> as you use URL string to make request, context will contain request as string. Workaround is to use Request object instead of URL string

oh yeah that totally makes sense now

> I think this is how original `fetch` was envisioned to work.

they don't advertise it much to be honest

---

for the record, I need this feature for logging purposes, I am migrating some library from `snekfetch` to `ofetch` and when there's an error there's logging that contains the request method and I wanted to keep this behavior since I think it's valuable.

logging the endpoint and returned body might not be enough given that the same endpoint will not do the same thing when requested with GET, PUT or POST.

thank you for your answer, I am marking this as resolved.

**Comment by KaKi87** [comment]
I think this issue should remain open because the `Request` workaround removes all the automation that we use `ofetch` for. Thanks

**Comment by phorcys420** [comment]
I do agree.

---

I took a quick glance at th ecode and I think ``context.options`` should be passed to ``createFetchError``.
https://github.com/unjs/ofetch/blob/19b79fa5cbf24cda0a81bf768c636e01eef82541/src/fetch.ts#L121C19-L121C35

---

Another (better) solution would be to simply use [``context.request``](https://github.com/unjs/ofetch/blob/19b79fa5cbf24cda0a81bf768c636e01eef82541/src/fetch.ts#L139C9-L139C9) instead of [``context.options``](https://github.com/unjs/ofetch/blob/19b79fa5cbf24cda0a81bf768c636e01eef82541/src/fetch.ts#L140) whenever writing the new parameters.

what I mean is that whenever a string is passed as the first argument, it gets turned into a ``Request`` automatically and ``ofetch`` adds the parameters to that ``Request`` object instead of ``context.options``

---

I am still willing to PR this if you feel like this is a valuable thing like I do, it's also pretty easy.

**Comment by phorcys420** [comment]
> I don't understand why would you need to have `Request` and `FetchOptions` objects in `FetchError` object, if you control the request and options that you send to server. Can you specify examples where this feature is needed?

simply put, the codebase is built in such a way that when the promise is resolved, there is no access to the request options.

**Comment by luizzappa** [comment]
looking for that too

**Comment by pi0** [comment]
Should be supported via `error.options` after #270 being released 👍🏼

**Comment by phorcys420** [comment]
thanks!
