### ISSUE TITLE
Mark `Headers` parameter of `createFetch` as optional

### ISSUE THREAD

**Issue by KaKi87** [unjs/ofetch#266]
### Describe the feature

As per https://github.com/unjs/ofetch/issues/260#issuecomment-1681345080.

Thanks

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by picunada** [comment]
Hello, I think u supposed to use `$fetch.create` or `ofetch.create` instead of `createFetch`,  as `createFetch` is more of a 'inside stuff' 

As I see, `$fetch.create` working as macros passing global parameters like Headers and default options for you.

**Comment by KaKi87** [comment]
No, please read the linked issue to understand what's this about.

**Comment by picunada** [comment]
> No, please read the linked issue to understand what's this about.

Sorry, my bad

So, this is how it's used by default:

```ts
export const fetch =
  _globalThis.fetch ||
  (() => Promise.reject(new Error("[ofetch] global.fetch is not supported!")));

export const Headers = _globalThis.Headers;

export const ofetch = createFetch({ fetch, Headers });
```
