### ISSUE TITLE
Allow using a single object as `ofetch` parameter

### ISSUE THREAD

**Issue by KaKi87** [unjs/ofetch#267]
### Describe the feature

Hello,

It would be nice to be able to optionally turn `ofetch(request, options)` into `ofetch(options)` with `options.request` in it.

Thanks

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. I think it might be a nice pattern too but adding to ofetch's core, might add additional bytecodes and type complexity. You can always create a wrapper util to do that 👍🏼

**Comment by KaKi87** [comment]
`ofetch` is already a wrapper.

I'm not gonna make a wrapper on a wrapper.

I guess I'll forget it, thanks anyway.
