### ISSUE TITLE
ofetch.native fails with: `'fetch' called on an object that does not implement interface Window.`

### ISSUE THREAD

**Issue by cosbgn** [unjs/ofetch#272]
### Environment

Nuxt 3.6.5 

### Reproduction

https://stackblitz.com/edit/github-9ukebr-xnzf5u?file=pages%2Findex.vue

### Describe the bug

ofetch.native fails with: `'fetch' called on an object that does not implement interface Window.`

### Additional context

You can reproduce it with:

```js
<template>
	<div>
	  <div>{{ res.fetch }}</div>

	  <hr />

	  <div>
		{{ res.ofetch }}
		// ofetch fails with: `Uncaught (in promise) TypeError: 'fetch' called on an object that does not implement interface Window.`
	</div>
	</div>
  </template>
  
  <script setup>
  const res = ref({ fetch: null, ofetch: null })
  onMounted(async () => {
	const url = 'https://jsonplaceholder.typicode.com/todos/1'
	res.value.fetch = await fetch(url).then((r) => r.json())
	res.value.ofetch = await $fetch.native(url).then((r) => r.json())
  })
  </script>
  
  ```

**Comment by pi0** [comment]
Hi dear @cosbgn. Thanks for making the reproduction. I have pushed a fix which will be available in next release 👍🏼 

It seems you are using an old version of nuxt 3 (3.0.0 betas) with older `ohmyfetch` dependency. Please consider using latest `nuxt` version (or edge channel https://nuxt.com/docs/guide/going-further/edge-channel)

**Comment by cosbgn** [comment]
Thanks a lot. I'm actually using the latest, I just found this stackblitz online and the error appeared also there, so it was easier to just fork that rather than building a new one.

Thanks again!
