### ISSUE TITLE
Property 'statusCode' does not exist on type 'FetchError<any>'

### ISSUE THREAD

**Issue by misbahansori** [unjs/ofetch#278]
### Environment

Node : v16.14.2
ofetch: "^1.3.2",

### Reproduction

```
try {
    await $fetch("/contact", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      baseURL: runtimeConfig.public.apiUrl,
      body: form.value,
    });
  } catch (error) {
    if (!(error instanceof FetchError)) throw error;

    if (error.statusCode !== 422) throw error;
              // ^Property 'statusCode' does not exist on type 'FetchError<any>'.ts(2339)
    errors.value = error.data.errors;
                                  // ^Property 'data' does not exist on type 'FetchError<any>'.ts(2339)
  }
  ```

### Describe the bug

After upgrading to version 1.3.2, the following error message appears. I can confirm that the error message does not appear in version 1.3.1.

**Comment by pi0** [comment]
Thanks for making issue. You can use new `IFetchError` type to fix. I will try to find a way to fix `FetchError` (class) types. We had to make this change to avoid unnecessary runtime overhead...

**Comment by sharifzadesina** [comment]
It was actually working before.
Now, even I can't access `response` property. Actually non of `IFetchError` properties.

**Comment by johannschopplich** [comment]
@misbahansori @sharifzadesina I had the same problem and provided a PR to ensure TypeScript understands and provides properties like `statusCode`, `statusMessage` etc.: #279 

For my own purposes before the PR gets merged (or a better solution found 😉), you can re-export the type:
```ts
export type { IFetchError as FetchError } from 'ofetch'
```

Which I did in my Nuxt API Party plugin: https://github.com/johannschopplich/nuxt-api-party/commit/181a5a0dfb1e494c571bd84f09cb9a5b9d61fd86

**Comment by misbahansori** [comment]
In the meantime, does anyone have a good approach to narrow the types within the catch block? Since the error type is `unknown` we need to narrow it down. currently, I'm using `error instanceof FetchError` which has a runtime implication.

**Comment by pi0** [comment]
Should be resolved by https://github.com/unjs/ofetch/pull/279
