### ISSUE TITLE
cors error when pass custom headers

### ISSUE THREAD

**Issue by ziaadini** [unjs/ofetch#283]
### Environment

chrome
nuxt: 3.7

### Reproduction

this is not okay: 
```
 $fetch("/course/index", {
          method: "get",
          headers:{Authorization:"Bearer "+authStore.getToken},
          baseURL:"http://localhost/api/web"
      }).then((response: any) => {
         console.log("response",response)
          return response
      });
```

but this is okay:

```
 $fetch.native("/course/index", {
          method: "get",
          headers:{Authorization:"Bearer "+authStore.getToken},
          baseURL:"http://localhost/api/web"
      }).then((response: any) => {
         console.log("response",response)
          return response
      });
```

### Describe the bug

if i don't pass any header it's okay in both cases, but when i passe any headers, it dos not.

**Comment by ariksubagia** [comment]
i'm encountering this bug now, it's a weird bug

**Comment by NozomuIkuta** [comment]
2 code samples looks identical, so would you fix it?

By the way, what kind of error did you get?

It would be also worth checking [Access-Control-Allow-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers).

**Comment by pi0** [comment]
I would appreciate it if you can provide a reproduction or your repository to track possible causes. 🙏🏼 (for anyone else facing this issue, feel free to open a new issue also if you have a repo)
