### ISSUE TITLE
Usage with MSW / patched fetch

### ISSUE THREAD

**Issue by meesvandongen** [unjs/ofetch#295]
### Environment

Node

### Reproduction

https://codesandbox.io/p/sandbox/stoic-https-6gjdtz?file=/index.js:14,16

```ts
import { setupServer } from "msw/node";
import { http, HttpResponse } from "msw";
import wretch from 'wretch'
import { ofetch, fetch, createFetch } from 'ofetch'
import got from 'got'

const server = setupServer(
    http.get('https://example.com', () => {
        return HttpResponse.text('1')
    })
)
server.listen();

console.table([
 ['fetch', await globalThis.fetch('https://example.com').then(res => res.text()).then(res => res === '1')],
 ['ofetch fetch', await fetch('https://example.com').then(res => res.text()).then(res => res === '1')],
 ['ofetch createFetch', await createFetch()('https://example.com').then(res => res === '1')],
 ['ofetch', await ofetch('https://example.com').then(res => res === '1')],
 ['wretch', await wretch('https://example.com').get().text().then(res => res === '1')],
 ['got', await got.get('https://example.com').text().then(res => res === '1')],
])
```

![CleanShot 2023-12-23 at 14 00 06@2x](https://github.com/unjs/ofetch/assets/904724/f2f9c044-59c3-4291-a19e-f44df7d93aa0)

### Describe the bug

When other tools patch fetch, the global instance of ofetch will have the original `fetch` instance. This will cause tools such as msw to not be able to intercept requests with ofetch. A workaround could be to only get the globalThis.fetch at request time if no other fetch is specified.

### Additional context

Users can work around this at this time by using the `createFetch` helper function.

**Comment by mohammadGh** [comment]
Thanks @meesvandongen for opening this issue, which is also a problem we have encountered. Dear @pi0 please let us know what is the best and efficient temporary solution to solve this problem until it is resolved?

**Comment by edumudu** [comment]
For anyone coming here, I found a hacky and pretty bad but functional way to workaround this for now using the `Proxy` constructor

```ts
function createMyFetch() {
  const newFetch = createFetch({
    fetch: globalThis.fetch,
    Headers: globalThis.Headers,
  });

  return newFetch.create({
    // ...default options
  });
}

const original = createMyFetch();

export const http = new Proxy(original, {
  apply(_, thisArg, argumentsList) {
    return Reflect.apply(createMyFetch(), thisArg, argumentsList);
  },
});
```

This will work with msw@2.0.8 and node@18.18.0. Its pretty bad since will be creating a new fetch every time, so you can merge the arguments instead of creating a new stance every time.

**Comment by rinux55** [comment]
Running into this issue as well, a fix or workaround for usage with `msw` would be greatly appreciated.

**Comment by stichingsd-vitrion** [comment]
> Running into this issue as well, a fix or workaround for usage with `msw` would be greatly appreciated.

Same here, not working with Nuxt in my case for MSW serverside outgoing calls

**Comment by dwightjack** [comment]
I think this same problem (even if not strictly an issue with ofetch) happens with Datadog RUM: https://github.com/unjs/ofetch/issues/339

**Comment by dwightjack** [comment]
I might have found a possible, non-breaking solution to this problem and [submitted a PR](https://github.com/unjs/ofetch/pull/377), but I wonder whether it is effective in all scenarios.

**Comment by artmizu** [comment]
I'm too humbly awaiting the solution, thank you, guys, for your time! Tried to [overcome the issue by myself](https://github.com/artmizu/nuxt-prometheus/issues/42), but for now don't see any available options.

**Comment by shunnNet** [comment]
For someone who stuck in Nuxt + ofetch, I have created a Nuxt module [nuxt-msw](https://github.com/shunnNet/nuxt-msw), which integrate msw with Nuxt.

**Comment by pi0** [comment]
Next version of ofetch will use patched fetch.

**Comment by marr** [comment]
> Next version of ofetch will use patched fetch.

Should this be closed now that https://github.com/unjs/ofetch/pull/377 landed?
