### ISSUE TITLE
Request to add a function

### ISSUE THREAD

**Issue by Rasool-deldar** [unjs/ofetch#298]
### Describe the feature

Please add the OnDownloadProgress and OnUploadProgress functions that are in the axios-http package to your package.
Also add the following objects.

// maxContentLength defines the max size of the http response content in bytes allowed in node.js
  maxContentLength: 2000,

  // maxBodyLength (Node only option) defines the max size of the http request content in bytes allowed
  maxBodyLength: 2000,

  // validateStatus defines whether to resolve or reject the promise for a given
  // HTTP response status code. If validateStatus returns true (or is set to null
  // or undefined), the promise will be resolved; otherwise, the promise will be
  // rejected.
  validateStatus: function (status) {
    return status >= 200 && status < 300; // default
  },

  // maxRedirects defines the maximum number of redirects to follow in node.js.
  // If set to 0, no redirects will be followed.
  maxRedirects: 5, // default

axios-http link:
https://axios-http.com/docs/req_config

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for the issue and feature request. Let's track it via https://github.com/unjs/ofetch/issues/45 👍🏼
