### ISSUE TITLE
How to reinitiate/resend a request like Axios?

### ISSUE THREAD

**Issue by TimGuendel** [unjs/ofetch#300]
Hi,

I have a onResponseError interceptor in which I would like to resend the original request after updating its headers with a new valid token. With Axios this was possible like this:

```
const originalRequestConfig = error.config;
// [...] Update the headers
return $axios.request(originalRequestConfig);
```

How do I achieve this with ofetch? 🤔

**Comment by frasza** [comment]
@TimGuendel Have you figured it out?

**Comment by TimGuendel** [comment]
I did. Well, sort of. I simply used retryStatusCodes and a onResponseError interceptor:

```
const opts: FetchOptions = {
    baseURL: config.public.apiBasePath,
    onResponseError,
    retryStatusCodes: [401]
}
globalThis.$fetch = ofetch.create(opts);
```

The first request fails because of a  401, the onResponseError interceptor is first executed. In there, I get a new token. Then ofetch retries the request. Hope this helps... 👋

**Comment by frasza** [comment]
@TimGuendel  Thanks, will try. Did you have usecase where multiple requests require token refresh but want to refresh on single one and retry all of them?

**Comment by TimGuendel** [comment]
I have not tried multiple requests, but I have a much bigger problem: https://github.com/unjs/ofetch/issues/318 😶
