### ISSUE TITLE
The body come to endpoint as [Object: null prototype] and data is in key not value

### ISSUE THREAD

**Issue by imcm7** [unjs/ofetch#301]
### Environment

Nuxt 3

### Reproduction

-

### Describe the bug

[Object: null prototype] {
  '{"email":"admin@test.com","password":"test"}': ''
}

**Comment by NozomuIkuta** [comment]
@imcm7 

Would you provide a reproduction so that we can understand your situation correctly?

**Comment by imcm7** [comment]
It id because i use headers from previous request which body is url encoded https://github.com/unjs/h3/issues/555
