### ISSUE TITLE
Access default options

### ISSUE THREAD

**Issue by KeJunMao** [unjs/ofetch#303]
### Describe the feature

Can we obtain the default options for the current instance in some way, just like axios

https://www.axios-http.cn/en/docs/config_defaults

I used Nuxt and modified `globalThis` The baseURL of the `$fetch`

However, in SSR, useFetch only uses the "/" prefix passed to determine whether it is a local request.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by KeJunMao** [comment]
If we can access the default options, Should `isLocalFetch` be determined after concatenating the baseURL?

https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/fetch.ts#L143-L148C6

**Comment by pi0** [comment]
Hi. Thanks for making this issue and followup PR. Modification of global options is a no goal for ofetch (and also Nuxt). Similar feature in axios and (nuxt axios module) proven to make code more unpredictable and less stable when any global side-effect can affect fetching behavior.

For ofetch, you can always create a new configured fetch instance using `ofetch.create()` and also for nuxt using `$fetch.create()`, or create a higher order composable (`useMyAPIFetch()`) that wraps and provides custom options base url. 

This is strictly a no-gloal for ofetch to consider. If you want more help to give some ideas how to support custom base url for nuxt, feel free to open a new discussion in nuxt/nuxt repository and ping me 👍🏼

**Comment by KeJunMao** [comment]
thank you, what about get only `defaults`?

**Comment by pi0** [comment]
Getting defaults could be nice but in order to prevent it's modification, we need to implement a nested "deep freeze" on object which adds runtime/bundle overhead. What usecases are you thinking for accessing (read-only) `defaults`?
