### ISSUE TITLE
Object literal may only specify known properties, and  agent  does not exist in type  FetchOptions<'json'> 

### ISSUE THREAD

**Issue by cdwmhcc** [unjs/ofetch#316]
### Environment

nodejs: 20.9.0
ofetch: 1.3.3

### Reproduction

``` ts
import { ofetch } from "ofetch"
import { HttpsProxyAgent } from "https-proxy-agent"

await ofetch("user", {
    agent: new HttpsProxyAgent("http://127.0.0.1:7890"),
})
```

### Describe the bug

![image](https://github.com/unjs/ofetch/assets/8030134/990c5469-aaaf-4394-b713-8cccaacf4b9b)

**Comment by treboryx** [comment]
I'm getting the same error even by using dispatcher and ProxyAgent from `undici`

**Comment by pi0** [comment]
#308 adds missing types
