### ISSUE TITLE
`undefined` responses when used with React Native

### ISSUE THREAD

**Issue by qnp** [unjs/ofetch#324]
### Environment

React Native (all versions)

### Reproduction

It is difficult to provide a react-native starter as I'm not a specialist, and it will require that you install and setup everything to start a react-native project. Instead, you could rely on my detailed investigation

### Describe the bug

Hi,

in the light of [this issue](https://github.com/unjs/ofetch/issues/293),

Looking deeper into the commit linked by @pi0 to close the issue, and having the same issue as @gtjamesa (responses are all `undefined`), it seems that this commit will not fix the `undefined` responses issue.

I dug into `ofetch` source code and did my own investigation. It appears that there is a boolean `hasBody` which checks if `response.body` exists, [as expected in fetch Response spec](https://developer.mozilla.org/en-US/docs/Web/API/Response), see: https://github.com/unjs/ofetch/blob/bb2d72baa5d3f332a2185c20fc04e35d2c3e258d/src/fetch.ts#L172-L173

Yet, only these fields are available in the `response` object returned by `fetch` in React Native:
`_bodyBlob`, `_bodyInit`, `bodyUsed`, `headers`, `status`, `statusText`, `type`.

Indeed, react-native [uses](https://github.com/facebook/react-native/commit/bccc92dfdd2d85933f2a9cb5c8d1773affb7acba) [whatwg-fetch polyfill](https://github.com/JakeChampion/fetch).

We can easily see [in whatwg-fetch source code](https://github.com/JakeChampion/fetch/blob/main/fetch.js) that all these keys are defined by the polyfill on `this`, but **not** `body`.

The correct answer would be to create an issue on `whatwg-fetch` so that they update their code and comply with Fetch API, and then create an issue on React Native to use this updated library, and then update React Native. Nevertheless, this process can take a while, and (as it is the case for our projects) many React Native projects are stuck to older versions because they depend on other libs that breaks and haven't updated yet and an update to the latest is very difficult.

The shorter answer would be to adapt `ofetch` so that it also checks specific `whatwg-fetch` fields in the response to know if a body is available.

What do you think ?

**Comment by wzulfikar** [comment]
I can confirm that the issue still exist today. Can replicate from default expo template and adding `ofetch` somewhere in the code.

```
npx create-expo-app myapp -t expo-template-blank-typescript
```

**Comment by joshmossas** [comment]
It seems this has long been an issue with react native
https://github.com/facebook/react-native/issues/27741

According to the author of whatwg-fetch. The react native team would need to make their own implementation of fetch since whatwg-fetch was intended for legacy browsers not other platforms
https://github.com/JakeChampion/fetch/issues/746#issuecomment-573251497

**Comment by joshmossas** [comment]
Sorry, I should note that these issues I linked are specific to streamed responses, but it seems react native has long had issues with the way "Fetch" has worked in their library.
