### ISSUE TITLE
Unsupported Engine Error for Node 20 and azure/msale 1.18

### ISSUE THREAD

**Issue by ZacJenks-campbell** [unjs/ofetch#352]
### Environment

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }

### Reproduction

In a very simple node installation using the following packages:
"packages": {
        "": {
            "name": "d365_data_sync",
            "version": "0.0.1",
            "license": "ISC",
            "dependencies": {
                "@azure/msal-node": "^1.17.2",
                "axios": "1.6.5",
                "dotenv": "^16.3.1",
                "fs": "~0.0.1-security",
            }
        },
run the npm i ofetch.  

### Describe the bug

When the install command is run the following warning appears in the console.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }

### Logs

```sh
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.4',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.2.3' }
npm WARN EBADENGINE }
```

**Comment by pi0** [comment]
I'm not sure this issue might be related to ofetch in any way we don't even require an engines field in this package.

Error is clear. (sadly) azure libs strictly don't support Node.js 20 you might need to downgrade to 18 or use `npm I --ignore-engines`
