### ISSUE TITLE
Support for array in query parameters in the get method

### ISSUE THREAD

**Issue by migueabellan** [unjs/ofetch#360]
### Describe the feature

I recently updated a project from `nuxt 2 with axios` to `nuxt 3 with ofetch` and I found a difference between axios and ofetch when passing an array in the query and **I don't know if it's a bug or a feature request**

```ts
await ofetch('https://jsonplaceholder.typicode.com/users', {
    method: 'GET',
    params: {
      items: ['one', 'two', 'three'],
    },
  });
```

**with axios**
`/endpoint?items[]=one&items[]=two&items[]=three`

**with ofetch**
`/endpoint?items=one&items=two&items=three`

I think that the keys must contain square brackets as the axios example. Is this a bug?

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-fu9w26?file=app.vue

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by manniL** [comment]
See https://github.com/unjs/ufo/issues/185 ☺️
