### ISSUE TITLE
Failed to upload Mega-sized base64 image 

### ISSUE THREAD

**Issue by syqaaa** [unjs/ofetch#368]
### Environment

chrome 121.0.6167.185 (64)

### Describe the bug

I use the put method to upload a base64 image, but cannot send a request if the size is megabytes. How Do I Change the Parameter Size Limit?

FetchError: [PUT] "https://......" <no response> Failed to fetch
    at async $fetch2 (ofetch.00501375.mjs?v=83ce1859:261:15)

**Comment by pi0** [comment]
Hi please share a reproduction of your project and deployment scenario so we can investigate and help 🙏🏼
