### ISSUE TITLE
Set cookies

### ISSUE THREAD

**Issue by MickL** [unjs/ofetch#382]
### Describe the feature

I have a login route that returns a session cookie but when sending subsequents requests the cookie is not set:

```ts
const loginResponse = await ofetch.raw('/login', {
      method: 'POST',
      body: {
        email: 'a@b.com',
        password: 'test123',
      },
    });
expect(loginResponse.status).toBe(204);

const securedRouteResponse = await ofetch.raw('/admin/products');
expect(securedRouteResponse).toBe(200); // -> 403
```

Unfortunately the cookie is never set. I tried to set option `credentials: 'include'` on both requests with no success. Am I missing something?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by 87xie** [comment]
Checking the `Set-Cookie` attributes, such as `Path`, `Domain`, `Expires`, etc, in the server response headers of the `/login` endpoint to ensure the cookie is stored correctly

**Comment by MickL** [comment]
Yes it works fine in browser and in Postman

**Comment by duy-dev** [comment]
I also have the same problem, the application runs fine locally but when deployed to Firebase it cannot get cookies 😥

**Comment by sonicjhon1** [comment]
Try with
```ts
const loginResponse = await ofetch.raw('/login', {
      method: 'POST',
      body: {
        email: 'a@b.com',
        password: 'test123',
      },
      credentials: "include",
});
```

**Comment by MickL** [comment]
You mean `credentials: include`? Thats what I tried as I wrote in the initial issue

**Comment by sonicjhon1** [comment]
> You mean `credentials: include`? Thats what I tried as I wrote in the initial issue

Yeah, is `access-control-allow-credentials` header set to true in the server?

**Comment by MickL** [comment]
It works in the browser and with Postman, just not in the test or an empty node script with ofetch.

**Comment by pratik149** [comment]
Facing the same issue. Did anyone figure this out? :(

**Comment by Aareksio** [comment]
`fetch` by design is not managing the cookies for you

---

What you are trying to accomplish is creating a stateful client, which shares state between subsequent requests. `fetch`, and by extension `ofetch`, is not designed to do this. Each request is independent. To accomplish your goal, a separate concept of "cookie jar" is required - a storage instance which is going to read response headers, persist cookies and set them on future requests. You can write it yourself or try open source pacakges.

I imagine using [fetch-cookie](https://www.npmjs.com/package/fetch-cookie) package with `ofetch` should look like this:

```ts
import { $fetch } from 'ofetch'
import makeFetchCookie from 'fetch-cookie'

const fetchWithCookies = makeFetchCookie($fetch.native)
const client = $fetch.create({ fetch: fetchWithCookies })
```

**Comment by MickL** [comment]
Thanks for the info!

Can we treat this issue as a feature request then? So `ofetch` will behave as a cookie jar, automatically setting cookies @pi0 ?

**Comment by duy-dev** [comment]
> I also have the same problem, the application runs fine locally but when deployed to Firebase it cannot get cookies 😥

After many days of researching, I also found the problem. Firebase only accepts one cookie named __session. Hope this information is useful to everyone. Details on this can be found here: https://firebase.google.com/docs/hosting/manage-cache?hl=en#using_cookies

**Comment by pi0** [comment]
@Aareksio is well explained, ofetch is stateless by design. 

However, i see good use cases for stateful cookie (most importantly for testing), therefore made new proposal (~> #435). With stateful instance, we can also register a hook that implements cookie support.
