### ISSUE TITLE
Missing types in node export

### ISSUE THREAD

**Issue by Aareksio** [unjs/ofetch#390]
### Environment

node 21

### Reproduction

https://unpkg.com/ofetch@1.3.4/dist/index.d.ts
https://unpkg.com/ofetch@1.3.4/dist/node.d.ts

### Describe the bug

node.d.ts is missing type exports present in index.d.ts

### Additional context

```diff
< export { C as CreateFetchOptions, g as Fetch, b as FetchContext, F as FetchError, d as FetchOptions, h as FetchRequest, f as FetchResponse, G as GlobalOptions, I as IFetchError, M as MappedResponseType, R as ResponseMap, e as ResponseType, S as SearchParameters, c as createFetch, a as createFetchError } from './shared/ofetch.8459ad38.mjs';
---
> export { F as FetchError, c as createFetch, a as createFetchError } from './shared/ofetch.8459ad38.mjs';
```

**Comment by makezi** [comment]
Can confirm that these types were previously exported in v1.3.3. Updated to v1.3.4 and now facing "Module 'ofetch' has no exported member FetchOptions" (Same as #395)
