### ISSUE TITLE
Inconsistent headers object returned after a retried request

### ISSUE THREAD

**Issue by cmgdragon** [unjs/ofetch#393]
### Environment

ofetch 1.3.4
node 20.12.2

### Reproduction

https://stackblitz.com/edit/vitejs-vite-53ww8b?file=main.js

Open the devtools console and click the POST REQUEST button to see the issue

You can see how the headers are being turned into a Headers object no matter the original input, making the headers not accesible anymore when the request loops back

### Describe the bug

coming from https://github.com/nuxt/nuxt/issues/27042

`$fetch` [is transforming the headers object](https://github.com/unjs/ofetch/blob/main/src/fetch.ts#L129) into a [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers) class if there's a body and the method is other than GET; so if headers are being added in the `onRequest` interceptor using normal object property accessors instead of the Headers constructor (as shown in the [`useFetch` documentation](https://nuxt.com/docs/api/composables/use-fetch) at the moment I'm writing this issue), when the request is retried and loops back, these are being added as extra properties of the Headers object and ignored later

The expected behavior would be that the headers object was consistent across retried requests, and even across all interceptors

I think the headers object should either be normalized or at least be clear that the Headers constructor is required for modifying the request inside interceptors

### Additional context

I came across this issue when I tried to refresh a JWT using the `retry` option along with the `onResponseError` interceptor: https://github.com/nuxt/nuxt/discussions/26991

I also tried to fix it in this commit, normalizing the headers before the retry and after the onRequest: https://github.com/cmgdragon/ofetch/commit/8954d8c2f828004c6af703579eab422ce7404bdf, though this solution isn't taking into consideration any other interceptor but `onRequest` for modifying the headers

**Comment by adamdehaven** [comment]
I came here to report the same issue (I think). 

Let's say I set an `Accept` header on a request.

If you set `retry: 1` (the default) you can see the on the first request the header is sent:

```typescript
onRequest({ request, options }: FetchContext) {
  options.headers = options.headers || {}
  console.log('onRequest', request, JSON.stringify(options.headers))
})
```

If the request fails, the same logging above ^ will log an empty object `{}` for the second request where `options.retry === 0`
