### ISSUE TITLE
Errors in Interceptors are silently handled

### ISSUE THREAD

**Issue by Disservin** [unjs/ofetch#396]
### Environment

v20.7.0
ofetch 1.3.4

### Reproduction

add an interceptor i.e. onresponse to the fetch instance
```js
  const apiFetch = ofetch.create({
    onResponse(ctx) {
     if (ctx.response._data?.hasOwn('message')) {
       // todo
     }
    },
  })
```

### Describe the bug

the above reproduction will silently handle the js error without throwing any error, which makes it rather difficult to spot this issue from a developer perspective.. ik that`hasOwn` needs to be called on `Object` it is just to highlight the issue

### Additional context

workaround is to wrap your custom interceptor code in a try and catch
```js
     try {
       if (ctx.response._data?.hasOwn('message')) {
           // todo
       }
      } catch (error) {
        console.error(error)
      }
```

**Comment by pi0** [comment]
Hi, i have added additional tests for hook errors (https://github.com/unjs/ofetch/commit/7ff4d1150f8badbde7068529998610264f5f7915) and it seems `.catch` properly captures errors within hooks as expected.

Please share a runnable reproduction if you still have issues 🙏🏼
