### ISSUE TITLE
Better Handle Support for Development Certificates

### ISSUE THREAD

**Issue by wavedeck** [unjs/ofetch#411]
### Environment

Runtime: Bun v1.1.18
Package: v1.3.4
OS: macOS Sonoma 14.5

-- Additional Environments --
Dotnet SDK: v8.0.302 
Nuxt: v3.12.3

### Reproduction

I've created a minimal reproduction repo here: https://github.com/wavedeck/issue-ofetch-selfsigned-cert

Follow the README to reproduce the error.

### Describe the bug

ASP.NET Core supports developing with https enabled locally using a generated self signed development certificate.
This is done using the dotnet cli with the `dotnet dev-certs https -t` command which generates and trusts a ssl certificate.

Https is required for some features (especially authentication, cookies and cors) in ASP.NET Core.

While regular "fetch" in the browser has no problem whatsoever connecting and getting back data, "ofetch" does not like using this development certificate at all and returns pretty uninformative errors using the `useFetch` composable in Nuxt 3.

ofetch, in a standalone repository, at least hints at the certificate by returning `unable to verify the first certificate`, which is however not the case in my actual Nuxt 3 project. (i guess something triggers a rerender, resulting in the less informative error)

Specifically, in my actual production code, i only get `<no response> fetch failed`, which took quite a while to figure out it's the self signed certificate...

This is very bad DX (developer experience) as this issue also isn't really well documented, neither in the ofetch repo nor the nuxt 3 documentation. I've first stumbled upon workarounds by going through the closed issues in the ofetch repository.

It would help immensly, if ofetch either works fine with self signed certificates without using workarounds such as specific environment variables, throws more informative error messages on re-renders in the Nuxt 3 composable, or this issue gets more noticeably documented (e.g. a yellow warning box on the Nuxt 3 docs, describing workarounds)

I know that the useFetch composable has a blue notice describing this in the Nuxt 3 api docs, but this should really also be in the regular docs and the getting started.

**Comment by pi0** [comment]
Thanks for writing up and I agree, DX of fetching backends with untrusted certificated is not nice. But it is also nothing we can fix in ofetch (or Nuxt) scope. Runtimes such as Bun, Deno, and Node.js (undici) should provide out of the box better DX like CLI flags to allow self-signed certificates just like Browser clients do.

If we do anything in ofetch core, it will be runtime specific and diverge from (runtime)native fetch behavior.
