### ISSUE TITLE
define url params using options

### ISSUE THREAD

**Issue by Ayax0** [unjs/ofetch#415]
### Describe the feature

I use ofetch in combination with nitro and nuxt. Here I often have the problem that I have the following routes, for example:
```
GET /api/product
GET /api/product/summary
GET /api/product/:productId
```

With the way Nitro handles the type safety, I then have the problem that if i use the following fetch request:
```ts
const productId = "aa00160f-6270-47c9-87e5-0938d7b4271b"
const { data } = useFetch(`/api/product/${productId}`)
```
In this case, the return type is the return type of both the `/api/product/summary` endpoint and the `/api/product/:productId` endpoint because the variable productId is of type string and could theoretically also contain `summary`. Thus typescript matches both routes.

I think it would be useful if I could simply specify `/api/product/:productId` as fetch route and then enter the value for this parameter in the options with e.g. 
```ts
const productId = "aa00160f-6270-47c9-87e5-0938d7b4271b"
const { data } = useFetch("/api/product/:productId", {
  params: { productId }
})
```
This would allow Nitro to better determine the effective endpoint and, in my opinion, would also be somewhat cleaner.

for me, param / params would be the perfect term here. However, since this alias has only just been removed, I don't know whether it would make sense to use it for another function. This could probably lead to certain conflicts. Here you could alternatively use something like `url` or `urlParams`.

any opinions?

so far i have solved the problem by using a small helper function:
```ts
function useObjectId(id: string) {
  return id as "__ObjectId__";
}

const productId = "aa00160f-6270-47c9-87e5-0938d7b4271b"
const { data } = useFetch(`/api/product/${useObjectId(productId)}`)
```
so the type of my request certainly does not match one of my endpoints and is therefore recognized correctly. but it is not a nice solution. maybe there is already a good solution for this problem and I am just too stupid :)

### Additional information

- [x] Would you be willing to help implement this feature?

**Comment by Thy3634** [comment]
https://github.com/unjs/ufo/issues/243

**Comment by pi0** [comment]
Thanks for the nice writeup. Since currently ofetch does not have any definition for how URLs are shaped it might be an opinionated addition so for the time being at least i think it is out of the ofetch scope.

you might use `onRequest` interceptor btw to implement a similar feature.
