### ISSUE TITLE
Error using $fetch.create using CJS modules.

### ISSUE THREAD

**Issue by BrandonlinU** [unjs/ofetch#44]
I was working in a Nuxt2 app using `ohmyfetch` in the background with a home-made module, but the Nuxt2 app displays me that the`$fetch` export has not the method `create`, so I investigate and I found that the CJS module (what it was imported by Webpack after the bundle process) it not exports the method.

## Steps to reproduce the error
1. Create a new JS proyect with the `ohmyfetch` dependency.
2. Create a `index.js` file with the following content.
```js
const { $fetch } = require('ohmyfetch')

const scopedFetch = $fetch.create({});
```
3. Try to run the file.

## What I was expected
It should not thrown an error.

## Error description
```
const scopedFetch = $fetch.create({});
                           ^

TypeError: $fetch.create is not a function
    at Object.<anonymous> (/home/bantonio/PhpstormProjects/test-ohmyfetch/index.js:3:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by jarekcieslak** [comment]
Same here with es module import...
I'm trying to do this:
```
import { $fetch } from 'ohmyfetch'

const apiFetch = $fetch.create({ baseURL: '/api' })
```

And error shown in the nuxt console is the same: 
```
 ERROR  ERROR in utils/fetch.ts:3:25                                                                                                                                                                                                                                            14:54:08
TS2339: Property 'create' does not exist on type '$Fetch'.
    1 | import { $fetch } from 'ohmyfetch'
    2 |
  > 3 | const apiFetch = $fetch.create({ baseURL: '/api' })
```

**Comment by jarekcieslak** [comment]
@BrandonlinU I actually got rid of the error by updating the dependency to the latest version. I was on 0.4.8 and updating to 0.4.14 fixed the error.

**Comment by BrandonlinU** [comment]
@jarekcieslak Your solution is correct, your error was because you are using ESM and you don't have the updated version, the `create` method was introduced in the version 0.4.13, but in my case I am in the version 0.4.14 using CJS modules and because the CJS proxy module does not export a `create` method Node complains about that.

**Comment by shinguweb96** [comment]
Working with Vite, with WebPack:
ohmyfetch__WEBPACK_IMPORTED_MODULE_1__.$fetch.create is not a function

```
import { $fetch } from "ohmyfetch"

export default defineNuxtPlugin(({ $config }) => {

    //@ts-ignore
    globalThis.$fetch = $fetch.create({`
    ...........
```

Trying in Nuxt Bridge

@BrandonlinU @jarekcieslak 
can someone help me pls?

**Comment by P4sca1** [comment]
@pi0 I am experiencing the same issue in Nuxt.js 2 using ohmyfetch 0.4.15.

`ohmyfetch__WEBPACK_IMPORTED_MODULE_3__.$fetch.create is not a function`

**Comment by BrandonlinU** [comment]
Yeah... that will not work. I tried the same way as you, but the CJS proxy use Promises because the ES Module specification says that a module CAN use a top-level await, so you can't be sure that a ES Module does not use Promises, but `$fetch.create()` is a syncronous method, not a async method just like `$fetch()` or `$fetch.raw()`. Try to run your code with my example code and print out the new scoped client: You must see `Promise { <pending> }` and if you try to use it Node complains about the scoped client is not a function.

**Comment by P4sca1** [comment]
@BrandonlinU I tried the change locally by editing the files in node_modules and it works fine for me.

**Comment by pi0** [comment]
As a workaround you can use ESM version:

```js
const { createFetch } = await import('ohmyfetch')
```

**Comment by P4sca1** [comment]
How would that work?

I tried the following in my nuxt 2 plugin without success:
```ts
const { $fetch } = await import('ohmyfetch')
const $api = $fetch.create(defaults)
```

```ts
const { fetch, Headers, createFetch } = await import('ohmyfetch')
const $api = createFetch({ fetch, Headers, defaults })
```

**Comment by P4sca1** [comment]
Another issue is that `FetchError` is not exported in CJS. Would it be possible to have the same exports for both CJS and ESM?

**Comment by m0dch3n** [comment]
I also experienced the same problems, tried the same solutions, only to finally detect, that by adding the create to cjs will end up as a promise later...


As I was in a typescript environment, it was even more difficult to find this, as I was using ohmyfetch on client side with esm, and on server side with cjs...

Client and Server both used the same code for the create...

Is there any other possible solution?

**Comment by m0dch3n** [comment]
@pi0 

is there a reason, why the cjs/* import the *,mjs files ?

Would it not be easier, to simply build a cjs version with the following `build.config.ts` ?

```javascript
import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  declaration: true,
  rollup: {
    emitCJS: true,
  },
  entries: [
    'src/index',
    'src/node',
    'src/undici'
  ]
})
```

I believe building it in CJS is the only possible solution afaik, because we cannot load mjs, without being async...

**Comment by vaaski** [comment]
I'm still getting this in 1.0.0 and I'm not sure what the issue is

**Comment by NozomuIkuta** [comment]
Possibly same as #198, to which a fix PR has been submitted.
