### ISSUE TITLE
Provide localAddress option?

### ISSUE THREAD

**Issue by luke358** [unjs/ofetch#445]
### Describe the feature

We need to be able to bind outgoing HTTP requests to particular network interfaces.

ofetch doesn't currently expose the localAddress option when creating an http request, which would allow us to accomplish our need.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi dear Luke. Unfortunately, it is not something within ofetch scope if `fetch` spec does not allow this.

Two places you might raise this requirement for `fetch` on servers:
- https://github.com/nodejs/undici
- https://github.com/wintercg/fetch
