### ISSUE TITLE
Set header X-XSRF-TOKEN from Cookie XSRF-TOKEN

### ISSUE THREAD

**Issue by k0mar12** [unjs/ofetch#50]
Hey there.

According to convenience, many libraries and frameworks, like `axios` and `angular`, automaticly passing headers X-XSRF-TOKEN from existing cookie XSRF-TOKEN.

For example, if i have cookie `XSRF-TOKEN=AAAAAAAAML`and making ajax request, library should set header `X-XSRF-TOKEN=AAAAAAAAML` 

Is it possible to make it ?

**Comment by Gospodin116** [comment]
Good afternoon. I had exactly the same problem. So far I've come up with the following approach:

Create utils:
`import {ofetch, FetchContext, FetchResponse} from 'ofetch';
import appConfig from '~/app.config';

const $api = ofetch.create({
    baseURL: appConfig.API_URL,
    credentials: 'include',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
    },

    onRequest({ options }): Promise<void> | void {
        let token: string|boolean = <string>useCookie('XSRF-TOKEN').value ?? false;  // Получаем токен из Cookie

        if (token) {
            options.headers = {
                ...options.headers,
                'X-XSRF-TOKEN': token
            }
        }
    },

    onRequestError(context: FetchContext & { error: Error }): Promise<void> | void {
        // console.log('onRequestError', context)
    },

    onResponse(context: FetchContext & { response: FetchResponse<ResponseType> }): Promise<void> | void {
        // console.log('onResponse', context)
    },

    onResponseError(context: FetchContext & { response: FetchResponse<ResponseType> }): Promise<void> | void {
        // console.log(context.response.status)
    },
});

export default $api;`

In the right place, import the utility and call:
`$api('/auth/login', {
        method: 'POST',
        body: state.form
    });`

Unfortunately, I haven't come up with a more convenient way, but I'm in the process of doing so. Hope it helps you.
I am sorry for my English. I am not a native English speaker.

**Comment by pi0** [comment]
Hi. Sorry for not responding for long time. I belive this is a nice feature but probably too much overhead for the ofetch core size. We might instead provide such functionality from higher order frameworks such as nuxt (via auth module)
