### ISSUE TITLE
$fetch using `globalThis` (not the polyfill)

### ISSUE THREAD

**Issue by peteromano** [unjs/ofetch#53]
Code seems to be doing the polyfill detection, but then $fetch still uses `globalThis` (and not the polyfilled variable; `Pv` in this case.)

This is macOs high sierra, safari 11 using a prod nuxt3 build (using browserstack to test)

![image](https://user-images.githubusercontent.com/392387/155803386-0046ac6e-81c1-468b-86a8-5202e8a59f65.png)

**Comment by pi0** [comment]
Nuxt 3 does not add a fetch polyfill for browsers. Are you doing this by yourself?

**Comment by peteromano** [comment]
@pi0 Nope, I'm not. My web app works in modern browsers but testing some other earlier browsers, this is one issue (globalThis not found), and it 100% comes from ohmyfetch, for the reason i mentioned...

The ployfill is clearly included in the preceeding LOCs before the immediate error, where the polyfill var is `Pv` (in my prod build), but the failing code still uses `globaThis` (it should use `Pv`.)

Im not doing that, ohmyfetch is. And this should be patched to fix that.

**Comment by peteromano** [comment]
Searching this codebase itself, you can see a polyfill exists:

![image](https://user-images.githubusercontent.com/392387/155835286-1a298a53-2fdf-4862-80a3-4ea9d4e342de.png)

**Comment by peteromano** [comment]
So theres likely an LOC that needs to use (underscore) _globalThis and not regular globalThis.

**Comment by peteromano** [comment]
@pi0 This line ends up in the nuxt prod build: https://github.com/unjs/ohmyfetch/blob/4b74e45f9989a993e725e7fe4d2e098442e457f1/src/undici.ts#L7

`export const fetch = globalThis.fetch || undiciFetch || createNodeFetch()`

Browsers that dont support globalThis will just fail on that. But https://github.com/unjs/ohmyfetch/blob/4b74e45f9989a993e725e7fe4d2e098442e457f1/src/index.ts uses a polyfill. Should https://github.com/unjs/ohmyfetch/blob/4b74e45f9989a993e725e7fe4d2e098442e457f1/src/undici.ts#L7 also use the polyfill?

**Comment by peteromano** [comment]
@pi0 would be a nice, simple fix (i imagine) that would open up a few more supported browsers.

**Comment by peteromano** [comment]
I was gonna say, it might not even necessarily be that the polyfill is needed, but that that part of the code shouldn't be part of the client build in general (maybe that's the issue?) The undici path is leaking into the client build but shouldnt be?

Maybe a boilerplate stackblitz of nuxt3 would repro the issue.. 

Safari 11.1.2

**Comment by pi0** [comment]
Hi. Sorry this issue is stalled. I believe with latest versions, we strictly use polyfills from `node-fetch-natvie` but please ping me to reopen if still have issues.
