### ISSUE TITLE
JSONP is not supported

### ISSUE THREAD

**Issue by dxhuii** [unjs/ofetch#56]
JSONP returns an object that is a blob, as follows.

![image](https://user-images.githubusercontent.com/2328917/159837938-50d80bcd-2bf5-4c3d-8883-820a6b029bae.png)

**Comment by NozomuIkuta** [comment]
ofetch supports only the following content type:

https://github.com/unjs/ofetch/blob/f27660eae1c8bde65cad64670f15a891c804c3ea/src/utils.ts#L24-L31

If the provided response type is other than those, it assumes that `blob` should be returned.

https://github.com/unjs/ofetch/blob/f27660eae1c8bde65cad64670f15a891c804c3ea/src/utils.ts#L44-L66

---

By the way, to be honest as a developer, although I don't know your situation in detail, it's no longer recommended to use JSONP for security reasons.

---

@pi0 

I will leave it to you: close as not planned or keep opened.

**Comment by pi0** [comment]
Thanks for opening issue @dxhuii. I agree with @NozomuIkuta that it is probably not a safe option to be built-in in ofetch. Still happy to discuss if you think is relevant feature.
