### ISSUE TITLE
`ohmyfetch` with `jest`

### ISSUE THREAD

**Issue by ThornWalli** [unjs/ofetch#57]
Hello,

have found a problem with `jest` and `ohmyfetch`. I came across this when using @nuxt/image in `jest`.

Is this perhaps due to the `cjs` build? There a `mjs` is loaded by dynamic import.

I created an [example repository](https://github.com/ThornWalli/jest-ohmyfetch-test) for this case. 

Gives this error message and from time to time `SEGMENT FAULT`.

![Ohne Titel 6](https://user-images.githubusercontent.com/8287751/159936485-7193fc14-c08f-4b93-b16e-de7504f82719.png)

Thanks!

---
I have updated our test again, replaced `jest` with `vitest`.
Now it works, but you should think that ohmyfetch also works in `jest`?

**Comment by NozomuIkuta** [comment]
@ThornWalli 

Your question seems to be about Jest (ts-jest) rather than ohfetch-specific.
You might want to ask the question in their repositories.

Please feel free to reopen this issue if you find it again that this issue happens only with ohfetch package.

**Comment by NozomuIkuta** [comment]
@ThornWalli 

Can I have your Node.js version, so that I can investigate this issue more deeply?

**Comment by pi0** [comment]
Latest version ships with both CJS and ESM. If jest is not supported yet, there is nothing more we can do sadly. Still please ping to reopen if encountering issues.
