### ISSUE TITLE
How to prevent custom headers transformed lowercase?

### ISSUE THREAD

**Issue by tsulatsitamim** [unjs/ofetch#71]
![image](https://user-images.githubusercontent.com/5946791/164600897-5538d640-54b4-47d3-80cd-876c34385841.png)
![2022-04-22_11-21](https://user-images.githubusercontent.com/5946791/164601373-69b4c5d8-c66c-4a74-954e-41080247fac0.png)

I try to send custom header, but it send in lowercase which my server doesn't accept it.

**Comment by 516310460** [comment]
nuxt3 issue: https://github.com/nuxt/framework/issues/6657

**Comment by 516310460** [comment]
The keys in the custom 'headers' will be wrapped by the' headers' object and automatically converted to lowercase

**Comment by NozomuIkuta** [comment]
Closed according to https://github.com/nuxt/framework/issues/6657#issuecomment-1222238122

Please let us know if you find a provider that cares case-sensitivity.
