### ISSUE TITLE
When using get request, "params = { skip: 0 }", 'skip' will be converted to http://xxx?skip, causing the request to fail

### ISSUE THREAD

**Issue by li-jingxuan** [unjs/ofetch#72]
[BUG]![image](https://user-images.githubusercontent.com/48175155/164953318-815803ed-955c-446d-9fa8-a6f27fb454dc.png)
When using get request, "params = { skip: 0 }", 'skip' will be converted to http://xxx?skip, causing the request to fail!!!

My current processing method: qs.stringify({ skip: 0 })

Expected result: http://xxxx?skip=0

**Comment by NozomuIkuta** [comment]
`encodeQueryItem` is a function of `unjs/ufo` package, and it has been fixed in the package.
Please upgrade `ohfetch` package and check it again.

If you still encounter the bug, please let us know by creating another issue with a reference to this issue.
