### ISSUE TITLE
Option to avoid OPTIONS request before making due to CORS?

### ISSUE THREAD

**Issue by serhez** [unjs/ofetch#77]
I'm attempting to make a POST request to a back-end API with a JSON body using `$fetch` (through Nuxt 3's `useLazyFetch`). This automatically triggers an OPTIONS request before making the POST request, due to CORS checks I am guessing. Is there a parameter I can set to avoid the OPTIONS request first?

In case of a negative answer, could we make this possible?

Thanks!

**Comment by danielroe** [comment]
This is what the browser uses to decide whether to make an OPTIONS request: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests.

You can avoid CORS by ensuring your request is a [simple request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).
