### ISSUE TITLE
The response header gets the custom header value always null

### ISSUE THREAD

**Issue by chenmaolan** [unjs/ofetch#87]
![image](https://user-images.githubusercontent.com/40062515/172135179-77c1efd0-8c83-4837-b6d9-d3343fc9f70a.png)
![image](https://user-images.githubusercontent.com/40062515/172137598-eede4ef9-6b15-44f5-bd46-af72ce4106da.png)

**Comment by HarmNullix** [comment]
In another issue ticket I saw someone mentioning something about all lower case, have you tried this?
**Dont know if it works!**

**Comment by NozomuIkuta** [comment]
@chenmaolan 

Is it possible to share a screenshot of network tab in browser devtool?
It would be a bug if you get `null` while the header is listed up in network log.

**Comment by NozomuIkuta** [comment]
@chenmaolan 

Let me close this issue for now, and please feel free to reopen this issue with a reproduction.
