### ISSUE TITLE
The object created by the class becomes '[object Object]' in body, not JSON

### ISSUE THREAD

**Issue by rudimadima** [unjs/ofetch#92]
Hi!

```
class SomeClass {
  x: number = 5;
}

const obj = new SomeClass();

console.log(obj); // SomeClass {x: 5}

function handleClick() {
  $fetch('http://localhost:7500/api/someurl', {
    method: 'POST',
    body: obj, // converted to string '[object Object]'
  })
  .then((result) => {
    console.log(result);
  })
  .catch((err) => {
    console.log(err);
  });
}
```
$fetch sends '[object Object]', not JSON.

Such ugly solution solves the problem:
```
  $fetch('http://localhost:7500/api/someurl', {
    method: 'POST',
    body: JSON.parse(JSON.stringify(obj)),
  })
```

Other solution of stange problem:
```
body: { ...obj },
```

**Comment by rudimadima** [comment]
Problem source: isJSONSerializable function from /src/utils.ts:
```
  return (val.constructor && val.constructor.name === 'Object') ||
   typeof val.toJSON === 'function'
```

**Comment by NozomuIkuta** [comment]
@pi0 

It would be appreciated if you let us know which the fact is: the conditional logic is intentional or could be improved.

If it's intentional, I'm glad to submit a PR to explain it in a part of README.

**Comment by pi0** [comment]
Hi sorry for not responding for long. In fact if you want to support serializable classes as body, they need to implement `toJSON` method. (PR welcome to improve docs and add an example 👍🏼 ) (closing for triage)
